---
homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_installed_packages:
  - docker
  - golang
  - nvm
  - pyenv
  - pipenv
  - nvim
  - minikube
  - kubectl
  - openshift-cli
  - terraform
  - transmission
  - youtube-dl

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  - google-chrome
  - slack
  - telegram-desktop
  - zoom
  - visual-studio-code
  - iterm2
  - notion
  - guitar-pro
  - musescore
  - copyclip
  - monitorcontrol
  - middleclick
  - balenaetcher
  - fantastical
  - google-drive
  - maccy
  - vanilla
  - shottr
  - rectangle
  - iina

pip_packages:
  - ansible-lint
