---
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions

homebrew_installed_packages:
  - docker
  - golang
  - int128/kubelogin/kubelogin
  - krew
  - kubectl
  - minikube
  - nvim
  - nvm
  - pdm
  - pipenv
  - rye
  - terraform
  - transmission
  - youtube-dl

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - anydesk
  - balenaetcher
  - bartender
  - discord
  - docker
  - drawio
  - dropbox
  - fig
  - firefox
  - google-drive
  - home-assistant
  - iterm2
  - kindle
  - lens
  - musescore
  - notion
  - nvidia-geforce-now
  - obsidian
  - pycharm-ce
  - rapidapi
  - rectangle
  - send-to-kindle
  - sourcetree
  - utm
  - visual-studio-code
  - zoom

mas_installed_apps:
  - { id: 497799835, name: "Xcode" }
  - { id: 430255202, name: "Mactracker" }
  - { id: 1153157709, name: "Speedtest" }
  - { id: 425264550, name: "Disk Speed Test" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 747648890, name: "Telegram"}
  - { id: 1086818840, name: "Rocket.Chat"}
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409183694, name: "Keynote" }
  - { id: 1278508951, name: "Trello" }
  - { id: 1444383602, name: "GoodNotes" }
  - { id: 1289197285, name: "MindNode" }
  - { id: 963034692, name: "Streaks" }
  - { id: 1006087419, name: "SnippetsLab" }
  - { id: 1496833156, name: "Playgrounds" }
  - { id: 1474335294, name: "GoodLinks" }
  - { id: 1529448980, name: "Reeder" }
  - { id: 408981434, name: "iMovie" }
  - { id: 1333542190, name: "1Password 7" }
  - { id: 1402042596, name: "AdBlock" }
  - { id: 1346247457, name: "Endel" }
  - { id: 1055511498, name: "Day One" }

dockitems_remove:
  - App Store
  - Launchpad
  - Maps
  - Messages
  - Podcasts
  - Подкасты
  - System Preferences
  - TV

dockitems_persist:
  - name: "Safari"
    path: "/Applications/Safari.app/"
    pos: 1
  - name: "Почта"
    path: "/Applications/Mail.app/"
    pos: 2
  - name: "Календарь"
    path: "/Applications/Calendar.app/"
    pos: 3
  - name: "Напоминания"
    path: "/Applications/Reminders.app/"
    pos: 4
  - name: "Заметки"
    path: "/Applications/Notes.app/"
    pos: 5
  - name: "Notion"
    path: "/Applications/Notion.app/"
    pos: 6
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 7
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 8
  - name: "Sourcetree"
    path: "/Applications/Sourcetree.app/"
    pos: 9
  - name: "Lens"
    path: "/Applications/Lens.app/"
    pos: 10
  - name: "RapidAPI"
    path: "/Applications/RapidAPI.app/"
    pos: 11
  - name: "SnippetsLab"
    path: "/Applications/SnippetsLab.app/"
    pos: 12
  - name: "NVIDIA GeForce NOW"
    path: "/Applications/NVIDIA GeForce Now.app/"
    pos: 13
  - name: "Telegram"
    path: "/Applications/Telegram.app/"
    pos: 14
  - name: "Discord"
    path: "/Applications/Discord.app/"
    pos: 15

dotfiles_repo: "ssh://git@gitlab.com/alenrig/dots.git"
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: "~/code/dots"
dotfiles_home: "~"
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .vimrc
  - .zshrc
  - .zprofile

zsh_plugins:
  - {repo: 'https://github.com/zsh-users/zsh-autosuggestions', dest: '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions'}
  - {repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git', dest: '~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting'}
  - {repo: 'https://github.com/dracula/zsh.git', dest: '~/.oh-my-zsh/custom/themes'}

vim_plugins:
  - {repo: 'https://github.com/jiangmiao/auto-pairs.git', dest: 'auto-pairs'}
  - {repo: 'https://github.com/scrooloose/nerdtree.git', dest: 'nerdtree'}
  - {repo: 'https://github.com/dracula/vim.git', dest: 'vim'}
  - {repo: 'https://github.com/bling/vim-airline.git', dest: 'vim-airline'}
  - {repo: 'https://github.com/vim-airline/vim-airline-themes.git', dest: 'vim-airline-themes'}
  - {repo: 'https://github.com/tpope/vim-commentary.git', dest: 'vim-commentary'}
  - {repo: 'https://github.com/tpope/vim-fugitive.git', dest: 'vim-fugitive'}
  - {repo: 'https://github.com/jeetsukumaran/vim-indentwise.git', dest: 'vim-indentwise'}
  - {repo: 'https://github.com/powerman/vim-plugin-ruscmd.git', dest: 'vim-plugin-ruscmd'}
  - {repo: 'https://github.com/tpope/vim-repeat.git', dest: 'vim-repeat'}
  - {repo: 'https://github.com/tpope/vim-surround.git', dest: 'vim-surround'}

pip_packages:
  - ansible-lint
