---
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions
  - hashicorp/tap
  - fluxcd/tap
  - railwaycat/emacsmacport

homebrew_installed_packages:
  - golang
  - gopls
  - grip  # emacs markdown preview
  - kubectl
  - int128/kubelogin/kubelogin
  - hadolint  # emacs dockerfile lint
  - hashicorp/tap/terraform
  - hashicorp/tap/terraform-ls
  - fluxcd/tap/flux
  - krew
  - minikube
  - nvim
  - nvm
  - openjdk
  - pdm
  - name: railwaycat/emacsmacport/emacs-mac
    install_options: "with-modules,with-native-compilation,with-xwidgets,with-natural-title-bar,with-imagemagick,with-mac-metal"
  - uv
  - virtctl

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - anydesk
  - appcleaner
  - balenaetcher
  - dbeaver-community
  - docker
  - drawio
  - dropbox
  - google-chrome
  - google-drive
  - hiddenbar
  - home-assistant
  - iterm2
  - lens
  - monitorcontrol
  - musescore
  - obsidian
  - rapidapi
  - rectangle
  - sourcetree
  - transmission
  - utm
  - visual-studio-code
  - zoom

mas_installed_apps:
  - name: "Xcode"
    id: 497799835
  - name: "Mactracker"
    id: 430255202
  - name: "Speedtest"
    id: 1153157709
  - name: "Disk Speed Test"
    id: 425264550
  - name: "WireGuard"
    id: 1451685025
  - name: "Telegram"
    id: 747648890
  - name: "Pages"
    id: 409201541
  - name: "Numbers"
    id: 409203825
  - name: "Keynote"
    id: 409183694
  - name: "Trello"
    id: 1278508951
  - name: "GoodNotes"
    id: 1444383602
  - name: "MindNode"
    id: 1289197285
  - name: "Streaks"
    id: 963034692
  - name: "GoodLinks"
    id: 1474335294
  - name: "Reeder"
    id: 1529448980
  - name: "iMovie"
    id: 408981434

dockutil_install: false
dockitems_remove:
  - App Store
  - Launchpad
  - Maps
  - Messages
  - Podcasts
  - Подкасты
  - System Preferences
  - TV

dockitems_persist:
  - name: "Safari"
    path: "/Applications/Safari.app/"
    pos: 1
  - name: "Почта"
    path: "/Applications/Mail.app/"
    pos: 2
  - name: "Календарь"
    path: "/Applications/Calendar.app/"
    pos: 3
  - name: "Напоминания"
    path: "/Applications/Reminders.app/"
    pos: 4
  - name: "Заметки"
    path: "/Applications/Notes.app/"
    pos: 5
  - name: "Obsidian"
    path: "/Applications/Obsidian.app/"
    pos: 6
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 10
  - name: "WebSSH"
    path: "/Applications/WebSSH.app/"
    pos: 11
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 12
  - name: "Sourcetree"
    path: "/Applications/Sourcetree.app/"
    pos: 13
  - name: "Lens"
    path: "/Applications/Lens.app/"
    pos: 14
  - name: "RapidAPI"
    path: "/Applications/RapidAPI.app/"
    pos: 15
  - name: "DBeaver"
    path: "/Applications/DBeaver.app/"
    pos: 16
  - name: "Telegram"
    path: "/Applications/Telegram.app/"
    pos: 20
  - name: "Видеоповтор iPhone"
    path: "/System/Applications/iPhone Mirroring.app"
    pos: 30

dotfiles_repo: "ssh://git@gitlab.com/alenrig/dots.git"
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: "~/Developer/dots"
dotfiles_home: "~"
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .vimrc
  - .zshrc
  - .zprofile

zsh_plugins:
  - repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions'
  - repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: '~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting'
  - repo: 'https://github.com/dracula/zsh.git'
    dest: '~/.oh-my-zsh/custom/themes'

vim_plugins:
  - repo: 'https://github.com/jiangmiao/auto-pairs.git'
    dest: 'auto-pairs'
  - repo: 'https://github.com/scrooloose/nerdtree.git'
    dest: 'nerdtree'
  - repo: 'https://github.com/dracula/vim.git'
    dest: 'vim'
  - repo: 'https://github.com/bling/vim-airline.git'
    dest: 'vim-airline'
  - repo: 'https://github.com/vim-airline/vim-airline-themes.git'
    dest: 'vim-airline-themes'
  - repo: 'https://github.com/tpope/vim-commentary.git'
    dest: 'vim-commentary'
  - repo: 'https://github.com/tpope/vim-fugitive.git'
    dest: 'vim-fugitive'
  - repo: 'https://github.com/jeetsukumaran/vim-indentwise.git'
    dest: 'vim-indentwise'
  - repo: 'https://github.com/powerman/vim-plugin-ruscmd.git'
    dest: 'vim-plugin-ruscmd'
  - repo: 'https://github.com/tpope/vim-repeat.git'
    dest: 'vim-repeat'
  - repo: 'https://github.com/tpope/vim-surround.git'
    dest: 'vim-surround'
