---
- name: Prepare Mac for Rock!
  hosts: localhost
  vars_files: config.yml
  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
    - geerlingguy.mac.dock
  tasks:
    - name: Install global Pip packages.
      ansible.builtin.pip:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
        version: "{{ item.version | default(omit) }}"
        executable: "{{ item.executable | default('pip3') }}"
      loop: "{{ pip_packages }}"
