---
- name: Prepare Mac for Rock!
  hosts: localhost
  vars_files: config.yml
  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
    - geerlingguy.mac.dock
    - geerlingguy.dotfiles
  tasks:
    - name: Install Vundle
      ansible.builtin.git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: '~/.vim/bundle/Vundle.vim'
        accept_hostkey: true
        clone: true
        version: master
    - name: Install global Pip packages.
      ansible.builtin.pip:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
        version: "{{ item.version | default(omit) }}"
        executable: "{{ item.executable | default('pip3') }}"
      loop: "{{ pip_packages }}"
