---
- name: Prepare Mac for Rock!
  hosts: localhost
  vars_files: config.yml

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
    - geerlingguy.mac.dock
    - geerlingguy.dotfiles

  tasks:
    - name: Install Vundle
      ansible.builtin.git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: '~/.vim/bundle/Vundle.vim'
        accept_hostkey: true
        clone: true
        version: master

    - name: Install Vim Plugins
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "~/.vim/bundle/{{ item.dest }}"
        clone: true
        version: master
      loop:
        - {repo: 'https://github.com/jiangmiao/auto-pairs.git', dest: 'auto-pairs'}
        - {repo: 'https://github.com/scrooloose/nerdtree.git', dest: 'nerdtree'}
        - {repo: 'https://github.com/dracula/vim.git', dest: 'vim'}
        - {repo: 'https://github.com/bling/vim-airline.git', dest: 'vim-airline'}
        - {repo: 'https://github.com/vim-airline/vim-airline-themes.git', dest: 'vim-airline-themes'}
        - {repo: 'https://github.com/tpope/vim-commentary.git', dest: 'vim-commentary'}
        - {repo: 'https://github.com/tpope/vim-fugitive.git', dest: 'vim-fugitive'}
        - {repo: 'https://github.com/jeetsukumaran/vim-indentwise.git', dest: 'vim-indentwise'}
        - {repo: 'https://github.com/powerman/vim-plugin-ruscmd.git', dest: 'vim-plugin-ruscmd'}
        - {repo: 'https://github.com/tpope/vim-repeat.git', dest: 'vim-repeat'}
        - {repo: 'https://github.com/tpope/vim-surround.git', dest: 'vim-surround'}

    - name: Install ZSH Plugins
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        accept_hostkey: true
        clone: true
        version: master
      loop:
        - {repo: 'https://github.com/zsh-users/zsh-autosuggestions', dest: '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions'}
        - {repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git', dest: '~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting'}
        - {repo: 'https://github.com/dracula/zsh.git', dest: '~/.oh-my-zsh/custom/themes'}

    - name: Install global Pip packages.
      ansible.builtin.pip:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
        version: "{{ item.version | default(omit) }}"
        executable: "{{ item.executable | default('pip3') }}"
      loop: "{{ pip_packages }}"
