---
- name: Prepare Mac for Rock!
  hosts: localhost
  vars_files: default.config.yml

  pre_tasks:
    - name: Include playbook configuration
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
    - geerlingguy.mac.dock
    - geerlingguy.dotfiles
    - etc
