---
- name: Download OMZ
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh 
    dest: /tmp/install.sh
    mode: "+x"

- name: Install OMZ
  command: sh /tmp/install.sh
  args:
    creates: ~/.oh-my-zsh

- name: Install Vundle
  ansible.builtin.git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: '~/.vim/bundle/Vundle.vim'
    accept_hostkey: true
    clone: true
    version: master

- name: Install Vim Plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "~/.vim/bundle/{{ item.dest }}"
    clone: true
    version: master
  loop: "{{ vim_plugins }}"

- name: Remove example.zsh file
  ansible.builtin.file:
    path: ~/.oh-my-zsh/custom/themes/example.zsh-theme
    state: absent

- name: Install ZSH Plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: true
    clone: true
    version: master
  loop: "{{ zsh_plugins }}"

- name: Install global Pip packages.
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default('pip3') }}"
  loop: "{{ pip_packages }}"
