---
- name: Add Emacs to Applications
  ansible.builtin.copy:
    src: /opt/homebrew/opt/emacs-mac/Emacs.app
    dest: /Applications/Emacs.app

- name: Clone DOOM
  ansible.builtin.git:
    repo: git@github.com:alenrig/doom.git
    depth: 1
    dest: ~/.emacs.d

- name: Clone DOOM settings
  ansible.builtin.git:
    repo: https://github.com/alenrig/doom
    dest: ~/.doom.d

- name: Install DOOM
  ansible.builtin.shell:
    cmd: ~/.emacs.d/bin/doom install --no-env
    creates: ~/.emacs.d/.local
